name: Eagle
version: 1.0.0
main: io.yodaka.eagle.EaglePlugin
api-version: 1.21
author: nedew
description: A competitive PvP plugin for Minecraft
api: "エディタ上でapiプロパティが無いとエラーが出るので書いているが、実際には使用されない。"

commands:
  eagle:
    description: Main Eagle plugin command
    usage: /eagle <subcommand>
    aliases: [e]
  join:
    description: Join the game
    usage: /join
  leave:
    description: Leave the game
    usage: /leave
  team:
    description: Team management
    usage: /team <subcommand>

permissions:
  eagle.admin:
    description: Allows access to admin commands
    default: op
  eagle.player:
    description: Allows basic player commands
    default: "op"
